version: "3.8"

name: mall
services:
  local-db:
    image: mysql:8.0
    #platform: linux/amd64
    environment:
      MYSQL_DATABASE: apidb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql